language: java
jdk: oraclejdk11
services:
  - mysql
before_install:
  - mysql -u root -e "CREATE USER 'springuser' IDENTIFIED BY '123';"
  - mysql -u root -e "CREATE DATABASE my_planner;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON my_planner.* TO 'springuser'@'%';"